name: Build Artifacts

on:
  push:
    branches: [main, master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-project
      - run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist
